export const CUSTOMER_TYPE = {
  CUSTOMER_REGULAR: 'CUSTOMER_REGULAR',
  CUSTOMER_PREMIUM: 'CUSTOMER_PREMIUM'
}

export const USER_TYPE = {
  EMPLOYEE: 'EMPLOYEE',
  AFFILIATE: 'AFFILIATE',
  GROCERY: 'GROCERY',
  CUSTOMER: 'CUSTOMER',
}

export const LOYALTY_YEAR_TO_BE_PREMIUM_CUSTOMER = 2;

export const DISCOUNT_AMOUNT = {
  AMOUNT: 100,
  DISCOUNT: 5
}

export const DISCOUNT_RATE = {
  EMPLOYEE: 0.3,
  AFFILIATE: 0.1,
  GROCERY: 0,
  CUSTOMER_REGULAR: 0,
  CUSTOMER_PREMIUM: 0.05,
}

export default {
  USER_TYPE,
  CUSTOMER_TYPE,
  LOYALTY_YEAR_TO_BE_PREMIUM_CUSTOMER,
  DISCOUNT_AMOUNT,
  DISCOUNT_RATE
}